@ /0000          ; INICIO DO PROGRAMA
SC /010          ; CHAMA SUBROTINA PRINCIPAL
HM /000          ; ENCERRA EXECUCAO

@ /010           ; SUBROTINA PRINCIPAL
K /0000          ; INICIALIZA VARIAVEIS
LD /090          ; CARREGA ENDERECO BASE (0100)
MM /092          ; ARMAZENA ENDERECO ATUAL
LD /094          ; INICIALIZA CONTADOR N=0
MM /096          ; ARMAZENA CONTADOR
LD /098          ; INICIALIZA SOMA=0
MM /09A          ; ARMAZENA SOMA

@ /020           ; LOOP DE CALCULO
LD /09A          ; CARREGA SOMA ATUAL
MM (092)         ; ARMAZENA NA MEMORIA
LD /092          ; CARREGA ENDERECO
AD /09C          ; INCREMENTA +2 BYTES
MM /092          ; ATUALIZA ENDERECO
LD /096          ; CARREGA CONTADOR
AD /09E          ; INCREMENTA N
MM /096          ; ATUALIZA CONTADOR
LD /09A          ; CARREGA SOMA
AD /096          ; SOMA += 2N (PARTE 1)
AD /096          ; SOMA += 2N (PARTE 2)
AD /0A0          ; SOMA += 1 (2N+1)
MM /09A          ; ATUALIZA SOMA
LD /096          ; CARREGA CONTADOR
SB /0A2          ; VERIFICA SE N=63
JZ /040          ; FINALIZA SE N=63
JP /020          ; REPETE LOOP

@ /040           ; FINALIZACAO
RS /010          ; RETORNA DA SUBROTINA

@ /090           ; DADOS/CONSTANTES
K /0100          ; ENDERECO INICIAL
K /0000          ; ENDERECO ATUAL
K /0000          ; CONTADOR (N)
K /0000          ; SOMA ACUMULADA
K /0002          ; PASSO DE MEMORIA (+2)
K /0001          ; INCREMENTO UNITARIO
K /003F          ; LIMITE (DEC 63)
K /0001          ; CONSTANTE 1
